################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.c \
../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.c 

C_DEPS += \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.d \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.d 

OBJS += \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.o \
./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.o 


# Each subdirectory must supply rules for building sources it contributes
Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/%.o Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/%.su Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/%.cyclo: ../Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/%.c Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/subdir.mk
	$(error unable to generate command line)

clean: clean-Practical_3F4-2f-Drivers-2f-CMSIS-2f-DSP-2f-Source-2f-StatisticsFunctions

clean-Practical_3F4-2f-Drivers-2f-CMSIS-2f-DSP-2f-Source-2f-StatisticsFunctions:
	-$(RM) ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.su
	-$(RM) ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d
	-$(RM) ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.d
	-$(RM) ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.d
	-$(RM) ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.su ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.cyclo ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.d ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.o ./Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.su

.PHONY: clean-Practical_3F4-2f-Drivers-2f-CMSIS-2f-DSP-2f-Source-2f-StatisticsFunctions

