################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

C++M_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CYCLO_FILES := 
OBJDUMP_LIST := 
CCM_DEPS := 
C_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
C_DEPS := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Practical_3A/Core/Src \
Practical_3A/Drivers/CMSIS/Core/Template/ARMv8-M \
Practical_3A/Drivers/CMSIS/Core_A/Source \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/JTest/src \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform/ARMCC \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform/ARMCLANG \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform/GCC \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/basic_math_tests \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/complex_math_tests \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/controller_tests \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/fast_math_tests \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/filtering_tests \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/intrinsics_tests \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/matrix_tests \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/statistics_tests \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/support_tests \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/transform_tests \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/BasicMathFunctions \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/ComplexMathFunctions \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/ControllerFunctions \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/FastMathFunctions \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/FilteringFunctions \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/HelperFunctions \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/Intrinsics \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/MatrixFunctions \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/StatisticsFunctions \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/SupportFunctions \
Practical_3A/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/TransformFunctions \
Practical_3A/Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example \
Practical_3A/Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example \
Practical_3A/Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example \
Practical_3A/Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example \
Practical_3A/Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example \
Practical_3A/Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example \
Practical_3A/Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example \
Practical_3A/Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example \
Practical_3A/Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example \
Practical_3A/Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example \
Practical_3A/Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example \
Practical_3A/Drivers/CMSIS/DSP/Source/BasicMathFunctions \
Practical_3A/Drivers/CMSIS/DSP/Source/CommonTables \
Practical_3A/Drivers/CMSIS/DSP/Source/ComplexMathFunctions \
Practical_3A/Drivers/CMSIS/DSP/Source/ControllerFunctions \
Practical_3A/Drivers/CMSIS/DSP/Source/FastMathFunctions \
Practical_3A/Drivers/CMSIS/DSP/Source/FilteringFunctions \
Practical_3A/Drivers/CMSIS/DSP/Source/MatrixFunctions \
Practical_3A/Drivers/CMSIS/DSP/Source/StatisticsFunctions \
Practical_3A/Drivers/CMSIS/DSP/Source/SupportFunctions \
Practical_3A/Drivers/CMSIS/DSP/Source/TransformFunctions \
Practical_3A/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/arm \
Practical_3A/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc \
Practical_3A/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/iar \
Practical_3A/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates \
Practical_3A/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/cifar10 \
Practical_3A/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/gru \
Practical_3A/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/Ref_Implementations \
Practical_3A/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test \
Practical_3A/Drivers/CMSIS/NN/Source/ActivationFunctions \
Practical_3A/Drivers/CMSIS/NN/Source/ConvolutionFunctions \
Practical_3A/Drivers/CMSIS/NN/Source/FullyConnectedFunctions \
Practical_3A/Drivers/CMSIS/NN/Source/NNSupportFunctions \
Practical_3A/Drivers/CMSIS/NN/Source/PoolingFunctions \
Practical_3A/Drivers/CMSIS/NN/Source/SoftmaxFunctions \
Practical_3A/Drivers/CMSIS/RTOS2/Source \
Practical_3A/Drivers/CMSIS/RTOS2/Template \
Practical_3A/Drivers/STM32F4xx_HAL_Driver/Src \
Practical_3A \
Practical_3F0/Core/Src \
Practical_3F0/Drivers/CMSIS/Core/Template/ARMv8-M \
Practical_3F0/Drivers/CMSIS/Core_A/Source \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/JTest/src \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform/ARMCC \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform/ARMCLANG \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform/GCC \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/basic_math_tests \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/complex_math_tests \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/controller_tests \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/fast_math_tests \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/filtering_tests \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/intrinsics_tests \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/matrix_tests \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/statistics_tests \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/support_tests \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/transform_tests \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/BasicMathFunctions \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/ComplexMathFunctions \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/ControllerFunctions \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/FastMathFunctions \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/FilteringFunctions \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/HelperFunctions \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/Intrinsics \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/MatrixFunctions \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/StatisticsFunctions \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/SupportFunctions \
Practical_3F0/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/TransformFunctions \
Practical_3F0/Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example \
Practical_3F0/Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example \
Practical_3F0/Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example \
Practical_3F0/Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example \
Practical_3F0/Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example \
Practical_3F0/Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example \
Practical_3F0/Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example \
Practical_3F0/Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example \
Practical_3F0/Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example \
Practical_3F0/Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example \
Practical_3F0/Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example \
Practical_3F0/Drivers/CMSIS/DSP/Source/BasicMathFunctions \
Practical_3F0/Drivers/CMSIS/DSP/Source/CommonTables \
Practical_3F0/Drivers/CMSIS/DSP/Source/ComplexMathFunctions \
Practical_3F0/Drivers/CMSIS/DSP/Source/ControllerFunctions \
Practical_3F0/Drivers/CMSIS/DSP/Source/FastMathFunctions \
Practical_3F0/Drivers/CMSIS/DSP/Source/FilteringFunctions \
Practical_3F0/Drivers/CMSIS/DSP/Source/MatrixFunctions \
Practical_3F0/Drivers/CMSIS/DSP/Source/StatisticsFunctions \
Practical_3F0/Drivers/CMSIS/DSP/Source/SupportFunctions \
Practical_3F0/Drivers/CMSIS/DSP/Source/TransformFunctions \
Practical_3F0/Drivers/CMSIS/Device/ST/STM32F0xx/Source/Templates/arm \
Practical_3F0/Drivers/CMSIS/Device/ST/STM32F0xx/Source/Templates/gcc \
Practical_3F0/Drivers/CMSIS/Device/ST/STM32F0xx/Source/Templates/iar \
Practical_3F0/Drivers/CMSIS/Device/ST/STM32F0xx/Source/Templates \
Practical_3F0/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/cifar10 \
Practical_3F0/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/gru \
Practical_3F0/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/Ref_Implementations \
Practical_3F0/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test \
Practical_3F0/Drivers/CMSIS/NN/Source/ActivationFunctions \
Practical_3F0/Drivers/CMSIS/NN/Source/ConvolutionFunctions \
Practical_3F0/Drivers/CMSIS/NN/Source/FullyConnectedFunctions \
Practical_3F0/Drivers/CMSIS/NN/Source/NNSupportFunctions \
Practical_3F0/Drivers/CMSIS/NN/Source/PoolingFunctions \
Practical_3F0/Drivers/CMSIS/NN/Source/SoftmaxFunctions \
Practical_3F0/Drivers/CMSIS/RTOS2/Source \
Practical_3F0/Drivers/CMSIS/RTOS2/Template \
Practical_3F0/Drivers/STM32F0xx_HAL_Driver/Src \
Practical_3F0 \
Practical_3F4/Core/Src \
Practical_3F4/Drivers/CMSIS/Core/Template/ARMv8-M \
Practical_3F4/Drivers/CMSIS/Core_A/Source \
Practical_3F4/Drivers/CMSIS/DAP/Firmware/Source \
Practical_3F4/Drivers/CMSIS/DSP/ComputeLibrary/Source \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_bayes_example/RTE/Device/ARMCM0 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_bayes_example/RTE/Device/ARMCM3 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_bayes_example/RTE/Device/ARMCM4_FP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_bayes_example/RTE/Device/ARMCM55 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_bayes_example/RTE/Device/ARMCM7_SP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_bayes_example \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example/RTE/Device/ARMCM0 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example/RTE/Device/ARMCM3 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example/RTE/Device/ARMCM4_FP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example/RTE/Device/ARMCM55 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example/RTE/Device/ARMCM7_SP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example/RTE/Device/ARMCM0 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example/RTE/Device/ARMCM3 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example/RTE/Device/ARMCM4_FP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example/RTE/Device/ARMCM55 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example/RTE/Device/ARMCM7_SP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example/RTE/Device/ARMCM0 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example/RTE/Device/ARMCM3 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example/RTE/Device/ARMCM4_FP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example/RTE/Device/ARMCM55 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example/RTE/Device/ARMCM7_SP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example/RTE/Device/ARMCM0 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example/RTE/Device/ARMCM3 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example/RTE/Device/ARMCM4_FP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example/RTE/Device/ARMCM55 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example/RTE/Device/ARMCM7_SP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example/RTE/Device/ARMCM0 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example/RTE/Device/ARMCM3 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example/RTE/Device/ARMCM4_FP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example/RTE/Device/ARMCM55 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example/RTE/Device/ARMCM7_SP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example/RTE/Device/ARMCM0 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example/RTE/Device/ARMCM3 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example/RTE/Device/ARMCM4_FP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example/RTE/Device/ARMCM55 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example/RTE/Device/ARMCM7_SP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example/RTE/Device/ARMCM0 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example/RTE/Device/ARMCM3 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example/RTE/Device/ARMCM4_FP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example/RTE/Device/ARMCM55 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example/RTE/Device/ARMCM7_SP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example/RTE/Device/ARMCM0 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example/RTE/Device/ARMCM3 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example/RTE/Device/ARMCM4_FP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example/RTE/Device/ARMCM55 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example/RTE/Device/ARMCM7_SP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example/RTE/Device/ARMCM0 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example/RTE/Device/ARMCM3 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example/RTE/Device/ARMCM4_FP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example/RTE/Device/ARMCM55 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example/RTE/Device/ARMCM7_SP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example/RTE/Device/ARMCM0 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example/RTE/Device/ARMCM3 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example/RTE/Device/ARMCM4_FP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example/RTE/Device/ARMCM55 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example/RTE/Device/ARMCM7_SP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_svm_example/RTE/Device/ARMCM0 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_svm_example/RTE/Device/ARMCM3 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_svm_example/RTE/Device/ARMCM4_FP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_svm_example/RTE/Device/ARMCM55 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_svm_example/RTE/Device/ARMCM7_SP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_svm_example \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example/RTE/Device/ARMCM0 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example/RTE/Device/ARMCM3 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example/RTE/Device/ARMCM4_FP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example/RTE/Device/ARMCM55 \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example/RTE/Device/ARMCM7_SP \
Practical_3F4/Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example \
Practical_3F4/Drivers/CMSIS/DSP/Source/BasicMathFunctions \
Practical_3F4/Drivers/CMSIS/DSP/Source/BayesFunctions \
Practical_3F4/Drivers/CMSIS/DSP/Source/CommonTables \
Practical_3F4/Drivers/CMSIS/DSP/Source/ComplexMathFunctions \
Practical_3F4/Drivers/CMSIS/DSP/Source/ControllerFunctions \
Practical_3F4/Drivers/CMSIS/DSP/Source/DistanceFunctions \
Practical_3F4/Drivers/CMSIS/DSP/Source/FastMathFunctions \
Practical_3F4/Drivers/CMSIS/DSP/Source/FilteringFunctions \
Practical_3F4/Drivers/CMSIS/DSP/Source/InterpolationFunctions \
Practical_3F4/Drivers/CMSIS/DSP/Source/MatrixFunctions \
Practical_3F4/Drivers/CMSIS/DSP/Source/QuaternionMathFunctions \
Practical_3F4/Drivers/CMSIS/DSP/Source/SVMFunctions \
Practical_3F4/Drivers/CMSIS/DSP/Source/StatisticsFunctions \
Practical_3F4/Drivers/CMSIS/DSP/Source/SupportFunctions \
Practical_3F4/Drivers/CMSIS/DSP/Source/TransformFunctions \
Practical_3F4/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/arm \
Practical_3F4/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc \
Practical_3F4/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/iar \
Practical_3F4/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates \
Practical_3F4/Drivers/CMSIS/NN/Source/ActivationFunctions \
Practical_3F4/Drivers/CMSIS/NN/Source/BasicMathFunctions \
Practical_3F4/Drivers/CMSIS/NN/Source/ConcatenationFunctions \
Practical_3F4/Drivers/CMSIS/NN/Source/ConvolutionFunctions \
Practical_3F4/Drivers/CMSIS/NN/Source/FullyConnectedFunctions \
Practical_3F4/Drivers/CMSIS/NN/Source/NNSupportFunctions \
Practical_3F4/Drivers/CMSIS/NN/Source/PoolingFunctions \
Practical_3F4/Drivers/CMSIS/NN/Source/ReshapeFunctions \
Practical_3F4/Drivers/CMSIS/NN/Source/SVDFunctions \
Practical_3F4/Drivers/CMSIS/NN/Source/SoftmaxFunctions \
Practical_3F4/Drivers/CMSIS/RTOS2/Source \
Practical_3F4/Drivers/CMSIS/RTOS2/Template \
Practical_3F4/Drivers/STM32F4xx_HAL_Driver/Src \
Practical_3F4 \

